# com.datamindhub.blog와 하위 패키지 로그 레벨 설정
logging:
  level:
    com.datamindhub.blog: debug
    # org.springframework.security: debug

    # ocalVariableTableParameterNameDiscoverer WARN 해결
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false  # JpaBaseConfiguration$JpaWebConfiguration WARN 해결