# com.datamindhub.blog와 하위 패키지 로그 레벨 설정
logging:
  level:
    com.datamindhub.blog: debug
    # org.springframework.security: debug
    # org.hibernate.SQL: DEBUG

    # ocalVariableTableParameterNameDiscoverer WARN 해결
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
spring:

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

  config:
    import:
      - classpath:secrets.yaml

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false  # JpaBaseConfiguration$JpaWebConfiguration WARN 해결

  security:  # OAuth2 설정
    oauth2:
      client:
        registration: #registration
          naver:
            client-name: naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-name: kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          google:
            client-name: google
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider: #provider
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
