logging:
  level:
    com.datamindhub.auth: debug
server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false  # JpaBaseConfiguration$JpaWebConfiguration WARN ??
jwt:
  issuer: test
  secret-key: test1234test1234test1234test1234test1234test1234