# com.cosmos.sns? ?? ??? ?? ?? ??
logging:
  level:
    com.cosmos.sns: debug
    # org.springframework.security: debug

    # ocalVariableTableParameterNameDiscoverer WARN ??
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false  # JpaBaseConfiguration$JpaWebConfiguration WARN ??